version: "3"
services:
  # PostGIS database
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - geoserver-net

  # GeoServer
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.x
    container_name: geoserver
    depends_on:
      - postgis
    environment:
      GEOSERVER_ADMIN_PASSWORD: geoserver
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: "*"  # Allows all origins
      CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,HEAD,OPTIONS"  # Allowed HTTP methods
      CORS_ALLOWED_HEADERS: "*"  # Allows all headers
      CORS_ALLOW_CREDENTIALS: "false"
    ports:
      - "8080:8080"
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
    networks:
      - geoserver-net

networks:
  geoserver-net:
    driver: bridge

volumes:
  postgis_data:
  geoserver_data: